name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["main", "first-iteration"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Github pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run ng -- deploy --repo="https://github.com/aartek/memory-card-game-generator.git" --base-href=/memory-card-game-generator/ --name=aartek --email=artek700@gmail.com